void f() const throw (std::runtime_error);
int main()
{
    f();
}
