void foo() {
    try {}    catch(Foo& bar) {}
}